# 1/4: Introduction, vectors, matrix and plotting 

This is the first in a series of four Jupyter notebooks on the use of Python. The scope is to introduce vectors,  matrices and plotting functionality. None of the assignments in this notebook will be graded. The intention is to provide a sandbox to freely, eagerly and curiously play around in. Supervision by the TAs will be assured.
    
## Guidelines 
<ul>
<li> Make sure to have the Anaconda distribution of Python installed on your laptop. See BrightSpace for instructions on how to install Anaconda. 
<li> Students with no or limited previous exposure to Python are encouraged to work through this notebook step by step before going to the next notebook. 
<li> Students with previous exposure to Python are encouraged to review the material as refresher before going to the next notebook.   
</ul>
</font>

## Import Libraries

To be able to work on this Jupyter notebook version 5.6 file containing Python version 3.8 coding, the following libraries must be imported:

In [1]:
import numpy as np
print("Succesfully imported %s -- Version: %s"%(np.__name__,np.__version__))
import scipy
print("Succesfully imported %s -- Version: %s"%(scipy.__name__,scipy.__version__))
import matplotlib.pyplot as plt
print("Succesfully imported %s"%plt.__name__)
import pandas as pd
print("Succesfully imported %s -- Version: %s"%(pd.__name__,pd.__version__))
import sympy as sym 
print("Succesfully imported %s -- Version: %s"%(sym.__name__,sym.__version__))
from scipy import optimize
print("Succesfully imported %s"%optimize.__name__)
from numpy import linalg as LA
print("Succesfully imported %s"%LA.__name__)
from mpl_toolkits import mplot3d
print("Succesfully imported %s"%mplot3d.__name__)

Succesfully imported numpy -- Version: 1.18.1
Succesfully imported scipy -- Version: 1.4.1
Succesfully imported matplotlib.pyplot
Succesfully imported pandas -- Version: 1.0.1
Succesfully imported sympy -- Version: 1.5.1
Succesfully imported scipy.optimize
Succesfully imported numpy.linalg
Succesfully imported mpl_toolkits.mplot3d


## Information on the libraries that were imported 

<li> Python: <a href="https://www.python.org"> Documentation </a> and 
             <a href="https://www.udemy.com/course/programming-numerical-methods-in-python"> Programming Numerical Methods in Python </a>

<li> IPython: <a href="https://ipython.org"> Documentation </a>
    
<li> Jupyter: <a href="https://jupyter-notebook.readthedocs.io/en/stable/"> Documentation </a>

<li> Numpy: <a href="https://numpy.org/doc/stable/user/quickstart.html"> Quickstart Tutorial </a>, <a href="https://numpy.org/doc/stable/user/absolute_beginners.html"> Absolute Basics </a> and <a href="https://numpy.org/doc/stable/user/tutorials_index.html"> Tutorials </a> 

<li> Scipy: <a href="https://docs.scipy.org/doc/scipy/reference/"> Reference and Tutorials </a> and <a href="http://scipy-lectures.org"> SciPy Lecture Notes </a>

<li> Matplotlib: <a href="https://matplotlib.org/users/index.html"> Users Guide </a>

<li> Pandas: <a href="https://pandas.pydata.org/docs/"> Documentation </a>  

<li> Sympy: <a href="https://docs.sympy.org/latest/index.html"> Documentation </a>

<li> Spyder: <a href="www.spyder-ide.org"> Documentation </a>
 
</ul>

 ## Where to find information?

 •	Talk to a teaching assistant in case that installation of Jupyter appears problematic;  


• Introductory Jupyter course on Linked-Inn learning: https://www.linkedin.com/learning/introducing-jupyter;

• Guide about Jupyter notebooks use in Code Academy: https://www.codecademy.com/articles/how-to-use-jupyter-notebooks. To find more information about Jupyter Notebooks, read their documentation at https://jupyter.readthedocs.io/en/latest/; 

• For information on a specific function in Jupyter, you can type its name with a question mark after it. Alternatively, Python has a built-in help() function that can give you information about any module, keyword, or topic that you might need to know about while writing your Python code; 

## Advantages of and alternatives for Jupyter

•	Jupyter is a free, open-source, interactive tool known as a computational notebook that can be used to combine live software code, computational output, equations, descriptive text and multimedia visualization resources in a single document, which users can both create and share.

•	The Jupyter Notebook is a powerful tool to develop and present data analysis projects. Its uses can include numerical simulation, statistical modeling, data visualization, machine learning, and much more. 

•	Jupyter Notebooks are an interactive web application that allows users to run structured but iterative Python scripts. In this way, it is possible for the user to write lines of Python code and run them one at a time. Then, if a change is needed, an edit and rerun of the program can be made, all in the same window.

• An exciting and recent development is the development of the programming language julia (julialang.org). Julia is developed in public domain and promises to combine the easy of use of a scripting language such as Matlab or Python, with the speed of the programming language such as C++. Although Julia is not (yet) a compulsory course requirement, D. Lahaye is excited to share this new development with you.

## Learn some basics of the Jupyter Notebook

• Take a User Interface Tour of Jupyter Notebook from Help on the menubar.

• Now select this cell and try making a cell below by yourself using the '+' sign in the toolbar above.

• Now cut that cell using the scissors symbol and put it above this cell using the paste symbol.

• Copy that cell and paste it below this cell.

• Now delete both cells by selecting the cell, then go to edit and delete the cells.

• You can also move cells up and down using the arrow symbols on the toolbar.

• Take a look at the Keyboard Shortcuts in help().

• Practice using all the options and see what else you can do with Jupyter Notebook.

• Do remember to save your progress from time to time to create checkpoints which you can revert to if anything goes wrong!

• Also it is recommended to import all the libraries before you start so you don't have to again and again in every section.

## The Jupyter Notebook as a advanced calculator 

•	Using the Notebook to perform simple arithmetic computations. For example:

In [2]:
print(2 + 2)

4


Now you give it a try:

•	Using the Notebook to assign values to variables and to perform computations using these variables. For example:

In [3]:
a = 1
b = 2
c=a+b

print('c =',c)

c = 3


Now you give it a try:

•	Try manipulating characters and strings in the Notebook. For example:

In [4]:

string_1  = "Example string #1"
string_2 = 'Example string #2'
#Both methods are equivalent.
#If a string is delimited with double quotes, 
#any double quotation marks within the string will need to be escaped with a backslash (\):
"My teacher said \"Don't forget your homework.\""

# Python does not have a Character data type. 
#To access individual characters within a string, use bracket notation. 
#Like lists, Python strings are zero-indexed, so the first character of a string can be accessed with [0]:
# For example:
string_3 = "This is a string."
first_letter = string_3[0]
print('First Letter:', first_letter)

#To access a range of letters from a larger string, use slicing:
#For Example:

first4letters =string_3[0:4]
print('First 4 Letters:' ,first4letters) 

#You can use + and * operators with strings
# for example:
first_name = "Luke"
last_name = " I am your father! "
fullname = first_name + last_name
print(fullname)

#Multiplication can be used to generate multiple copies of strings:
#for example:

string_a= 'a'
string_a_TenTimes = string_a*10
print(string_a_TenTimes)

#Many basic string manipulation tasks can be handled with built-in methods.
#For example, to convert a string to uppercase letters, use upper:
print(string_a.upper())

#To remove extra whitespace from the beginning or end of a string, use strip:

string_4= '       Example       '
print(string_4.strip())

#trings can be split into a list of substrings with split. 
#By default, Python will use a blank space as a delimiter, 
#which is useful for splitting a sentence into individual words:
string_5 = 'This string have 5 words'
print(string_5.split())

#The inverse operation of split is join.

First Letter: T
First 4 Letters: This
Luke I am your father! 
aaaaaaaaaa
A
Example
['This', 'string', 'have', '5', 'words']


Now you give it a try:

•	Try simple while-loops, for-loops and if-then-else tests in the Notebook. For example:

In [5]:
#The While loop will remain active if the condition are true.
# for example:

count = 0
while count < 3:
    count = count + 1
    print(count)
# This loop will run 3 times.
#Each time will add 1 to the count and print the value it's value.

#The for loop will run a finite numbers of iterations.
#for example:

example = 'four'
for x in example:
    print(x)

#This loop will run 4 times. 
#Each time for every character in the variable.

#An "if statement" is written by using the if keyword.
#for example:

a = 5
b = 10
if b > a:
  print("b is greater than a")


#The elif keyword is pythons way of saying 
#"if the previous conditions were not true, then try this condition".
#for example:

a = 10
b = 10
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

#The else keyword catches anything which isn't caught by the preceding conditions.


a = 10
b = 5
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

1
2
3
f
o
u
r
b is greater than a
a and b are equal
a is greater than b


Now you give it a try:

• Try manipulating lists of items by adding and removing elements from lists and iterating over lists. For example:

In [6]:
# To create a list (collection of items that are ordered and changeable):

months = list()
months.append('January')
months.append('February')
months.append('March')
months.append('April')

print(months)
print(len(months))


#To iterate for every item in a list you can use a for loop

for i in months:
    if i == 'March' :
        print(i)
print(months[1:3])


#To remove an item from a list:

months.remove('March')
print(months)

#It is important to distinguish between Python lists and vectors/matrices in Python.


['January', 'February', 'March', 'April']
4
March
['February', 'March']
['January', 'February', 'April']


Now you give it a try:

## Constructing vectors 

• Use the function np.array() to create the row vector a = [10, 20, 30] and print to screen the first, first two, last and last two elements.

Do take a look at help(np.array) or https://numpy.org/doc/stable/reference/generated/numpy.array.html to learn how to use this function to build a vector. It is extremely important for this course and you will be using it a lot.

•	Now use function np.array() to create a column vector b containing the same elements as the previous vector a. Compare the syntax of a row vector and a column vector. Use the transpose() command to convert a row vector into a column vector, or vice versa. 

• Create subvectors containing different elements of the vector a. For example: 

In [7]:
#To create a new vector containing the first and second terms of the vector b:
b = np.array([[10],[20],[30]])
c=b[0:2]

print('c =',c) #Notice that this will return all elements starting from the number before the colon (0, or the first element) up to but not including the index after the colon (2). 


c = [[10]
 [20]]


Now you give it a try, by creating subvectors containing the last and last two elements of the vector a:

• Form a row vector with all three components equal to one and another with all elements equal to zero. To do this, take a look at help(np.zeros) and help(np.ones) and learn how to use these two different functions to obtain the desired vectors, as they can be are very useful when working with large vectors or matrices.


## Operations on vectors 

• Python allows to add row and column vectors to form a resulting matrix. For example: 

In [8]:
# For the column vector b = np.array([[10],[20],[30]]) and the row vector a = np.array([10,20,30]), the matrix ba = b + a can be computed:

b = np.array([[10],[20],[30]])
a = np.array([10,20,30])
ba=b+a

print('ba = ', ba)

ba =  [[20 30 40]
 [30 40 50]
 [40 50 60]]


Now you give it a try:

•	Given the column vector a = np.array([[10],[20],[30]]), compute the new vector 3*a.

• Given the column vector a = np.array([[10],[20],[30]]), compute the min, max and norm (distance to zero) of the vector a. Hint: There are functions from numpy that can be used to solve this.

•	Given the column vector a = np.array([[10],[20],[30]]) and the column vector b = np.array([[.1],[.2],[.3]]), compute the new vector a+b. 

 •	Given the column vector a = np.array([[10],[20],[30]]) and the column vector b = np.array([[.1],[.2],[.3]]), compute the inner product of a and b using the function np.inner() for the multiplication of matrices.

•	Given the column vector a = np.array([[10],[20],[30]]) and the column vector b = np.array([[.1],[.2],[.3]]), compute point-wise multiplication (*) of a and b.

•	Given the column vector a = np.array([[10],[20],[30]]) and the column vector b = np.array([[.1],[.2],[.3]]), compute the matrix product using np.dot(a,transpose(b)). Give the size of this matrix. Explain your findings.

Do learn about np.dot function here: https://numpy.org/doc/stable/reference/generated/numpy.dot.html, as it is another important function you will be using quite a bit in the future.

## Plotting vectors

• Plot the column vector a = np.array([[10],[20],[30]]). Type help(plt.figure), help(plt.subplots), help(ax.plot) and help(plt.show) to learn about the various possibilities available for obtaining a graph.

## Plotting functions in one variable

• Create the vector x with terms from 0 to 2 * np.pi with an increment of np.pi/100 and the vector y = np.sin(x). Now plot y vs. x. Add an x-axis label, y-axis label and a title to this plot. Next create the vector x1 = [0, np.pi/2, np.pi, 3 * np.pi/4, 2 * np.pi] and the vector y1 = np.sin(x1) and generate another plot of y1 vs. x1 superimposed on the previous plot.

•	Create the vector x with terms from -3 to 3 with an increment of 0.01 and the vector y = x*x (using the point-wise or element-wise multiplication of the x with x). Explain why the point wise multiplication is required here. 

## Constructing Matrices

• Use help(np.array) and help(np.matrix) to learn about two different ways to create a matrix. Generate the matrix A = [[1, 2, 3], [2, 4, 8], [3, 9, 27]], and then retrieve (or print to screen) both the first row and the last column of A. There are multiple ways to achieve this, such as using a list and a for loop.

• Given the matrix A = np.array([[1, 2, 3], [2, 4, 8], [3, 9, 27]]), retrieve (or print to screen) the diagonal of A (using the np.diagonal() function), the lower triangular part of A (using the function np.tril()) and then the upper triangular part of A (using np.triu()).

• Given the matrix A = np.array([[1,2,3],[2,4,8],[3, 9, 27]]), create and print to screen the matrix B = np.transpose(A) and the matrix C = np.transpose(B).

• Use the function np.zeros() to create a 3-by-3 matrix with all elements equal to zero.

• Use the function np.eye() to create the 3-by-3 identity matrix.

## Operations on Matrices 

•	Given the matrix A = np.array([[1, 2, 3],[ 2, 4, 8],[ 3, 9, 27]]), compute the new matrix 5*A.

•	Given the matrix A = np.array([[1, 2, 3],[ 2, 4, 8],[ 3, 9, 27]]), find the min, max, and norm of the matrix A (you will learn more about matrix norms very soon) using the functions max(), min() and LA.norm(). 

•	Given the matrix A = np.array([[1, 2, 3],[ 2, 4, 8],[ 3, 9, 27]]) and the matrix B = np.eye(3), compute the new matrix C = A+B and C = B+A. Explain what you observe.

•	Given the matrix A = np.array([[1, 2, 3],[ 2, 4, 8],[ 3, 9, 27]]) and the matrix B = np.ones(3), compute the new matrix C = A * B and C = B * A. Use the definition of the matrix-matrix product to explain your findings.

•	Given the matrix A = np.array([[1, 2, 3],[ 2, 4, 8],[ 3, 9, 27]]), compute the new matrix C= A * A (observe the point wise multiplication) and the new matrix D = np.dot(A,A). Explain your findings using again the definition of the matrix-matrix product. 

• Starting from matrix A construct three different versions of a matrix B that contains all the elements larger or equal to 5. First, using a double-for loop. Second, without a for-loop. Third, using a single for-loop by iterating over rows or columns.   

•	Given the matrix A = np.array([[1, 2, 3],[ 2, 4, 8],[ 3, 9, 27]]) and the vector b = np.array([[1],[1],[1]]), compute the number np.dot(np.dot(np.transpose(b),A),b). Compare your answer with sum(sum(A)). Explain your findings.

•	Use the funtion reshape() to construct matrices from vectors and the other way around as well.

## Triangular matrices  

• Given the lower triangular matrix A = np.array([[1,0,0],[2,4,0],[3, 9, 27]]), use the function np.linalg.eig() to compute the eigenvalues of the matrix A. Compare the eigenvalues with diagonal entries of A.

• Given the lower triangular matrix A = np.array([[1, 0, 0 ],[ 2, 4, 0],[ 3, 9, 27]]), compute and print to screen the new C = A * A (Try both point wise and matrix multiplication). What do you observe about the triangular structure of C? Compute the eigenvalues of C and compare with the diagonal entries.

• Repeat what you did above for C = AAA, C=pow(A,3), C=pow(A,4), C = pow(A,5) and C=pow(A,6).

• Repeat what you did above for the upper triangular matrix A = np.array([[1, 2, 3],[0, 4, 8],[0, 0, 27]]).

## Particular Tridiagonal Matrix - One Dimensional Poisson Matrix 

The scope of this assignment is to construct a particular tridiagonal matrix A that will be used in the future of this course. Assume that u(x) is a function in x on the domain where 0 <= x <= 1. The matrix A that we construct in this assignment allows to compute an approximation for minus one times the double derivative *(-d^2u/dx^2)*. This approximation to the double derivative is computed assuming a uniform (or equidistant) sampling of the interval 0 <=x <= 1. 

1. Given a value for N (e.g. N=5 or higher), set the vector e = np.ones((N+1).dtype=int). Then e is a row vector of length N+1 with all elements (or components) equal to 1.
2. Next, set A = np.zeros((N+1,N+1),dtype=int), then subtract np.diag(e[0:-1],k=0) from A[0:N,1:N+1] and similarly subtract np.diag(e[0:-1],k=0) from A[1:N+1,0:N]. 
3. Add 2*np.diag(e) to A.
4. Use the command plt.spy(scipy.sparse.csr_matrix(A)) (see help plt.spy) to view the non-zero structure of the matrix A.  

5. Next set A = (N) ** 2 * A (every element of A is thus multiplied with N^2).
6. Next set A[0,0] = 1 and A[0,1] = 0; (in this way the first row of A is modified). 
7. Next set A[-1,-1] = 1 and A[-1,-2] = 0; (in this way the last row of A is modified).
8. Next set x = np.linspace(0,1,num=N+1) (x is thus the coordinates of the points along the x-direction at intervals of 1/N). 
9. Set u = x * np.sin(np.pi * x); (observe the point wise multiplication of two vectors). 
10. Compute using pen and paper (or using the symbolic toolbox) minus one times the second order derivative - d^2u/dx^2 and plot this function. 
11. Compute the product of the matrix A and the vector u and plot the result and compare with the previous graph. Discuss your findings. 

We will define the matrix A to be the one-dimensional Poisson matrix and consider A as the output of a function that will be defined as poisson1d(N) in the next introduction notebook. Observe (again) that the size of A is (N+1)-by-(N+1). It appears that the fan club of this matrix goes well beyond the circles of the ANM course. 

## Plotting functions in two variables 

• Read the documentation of the Python funtion np.meshgrid() to plot the function u(x,y) = 16 * x * (x-1) * y * (y-1) on the unit square, i.e., the domain defined by 
0 <= x <= 1 and 0 <= y <= 1.

## Kronecker Product of Matrices 

•	Given the matrix A = np.array([[1, 2, 3],[ 2, 4, 8],[ 3, 9, 27]]) and the matrix B = np.ones(3), compute the Kronecker product of A and B using the Python np.kron() function. Observe that np.kron(A,B) and np.kron(B,A) differ; that is, the order of the factors does matter.

## Penta-Diagonal Matrix

The scope of this assignment is to extend the construction of the Poisson matrix (see above) from one to two spatial dimensions.

1. Set N = 3 (or any alternative value).  
2. Set x = np.linspace(0,1,num=N+1), y = np.linspace(0,1,num=N+1) and [X,Y] = np.meshgrid(x,y). Observe that X and Y are matrices of size (N+1)-by-(N+1). 
3. Set U = 16 * X * (X-1) * Y * (Y-1).  
4. Set A = poisson1d(N) (see above) and I=np.ones((N+1,N+1),dtype=int) (I is here the (N+1)-by(N+1) identity matrix)
5. Set the matrices B1= np.kron(A,I), B2 = np.kron(I,A) and B = B1+B2.
6. Plot the sparsity pattern of the matrix B1, B2 and B using the plt.spy command. Explain your findings.
7. Set u = np.reshape(U,(N+1) ** 2,1) (u is here a vector with (N+1)^2 components)
8. Set v1 = np.dot(B1,u), v2 = np.dot(B2,u) and v = np.dot(B,u). Find the size of v1, v2 and v. 
9. Set V1 = np.reshape(v1,N+1,N+1), V2 = np.reshape(v2,N+1,N+1) V = np.reshape(v,N+1,N+1).  
10. Use the meshgrid command to plot U, V1, V2 and V as a function on x and y. Make sure to properly label the x and y axis. Explain your findings.  

The matrix B is a close ally of the one-dimensional Poisson matrix A and will resurface during ANM and beyond. We will refer to B as the two-dimensional Poisson matrix and consider B as the output of a function that will be defined as poisson2d(N) in the next introduction notebook. Observe (again) that the size of B is (N+1)^2-by-(N+1)^2. 

## Broadcasting

• Binary operation on arrays are performed elementwise by Python. This means that when arrays of different sizes are involved in a binary operation, broadcasting is used. For example:

In [9]:
#Below, A is a 5 x 5 array whereas b is just a number. Here, b has been broascasted into a 5 x 5 array of which every value is 5.

A = np.ones((5,5))
print(A)
b=5
print(b)
print(A + b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
5
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


Now you give it a try:

More information about constructing arrays with different shapes and how they are managed by Python during arithmetic operations: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting